name: Gemini CLI Example

on:
  pull_request:
    branches: [ main ]

jobs:
  summarize-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/run-gemini-cli@main
        with:
          prompt: "a 'Summarize the changes in this PR'"
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
